// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment1PAPYRUS;

/************************************************************/
/**
 * 
 */
public class Bank {
	/**
	 * 
	 */
	public EMap counts;

	/**
	 * 
	 */
	public void Bank() {
	}

	/**
	 * 
	 * @param r 
	 * @param n 
	 * @return 
	 */
	public EBoolean canGive(Resource r, EInt n) {
	}

	/**
	 * 
	 * @param p 
	 * @param r 
	 * @param n 
	 */
	public void give(Player p, Resource r, EInt n) {
	}
}
