// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment1PAPYRUS;

/************************************************************/
/**
 * 
 */
public class Board {
	/**
	 * 
	 */
	public Tile[] tiles;
	/**
	 * 
	 */
	public Node[] nodes;
	/**
	 * 
	 */
	public Edge[] edges;
	/**
	 * 
	 */
	public EInt[] tileNodes;

	/**
	 * 
	 * @param tiles 
	 * @param nodes 
	 * @param edges 
	 * @param tileNodes 
	 */
	public void Board(Tile[] tiles, Node[] nodes, Edge[] edges, EInt tileNodes) {
	}

	/**
	 * 
	 * @param tileId 
	 * @return 
	 */
	public Tile tile(EInt tileId) {
	}

	/**
	 * 
	 * @param nodeId 
	 * @return 
	 */
	public Node node(EInt nodeId) {
	}

	/**
	 * 
	 * @param edgeId 
	 * @param Parameter1 
	 */
	public void edge(EInt edgeId, Edge Parameter1) {
	}

	/**
	 * 
	 * @param tileId 
	 * @return 
	 */
	public EInt[] nodesAroundTile(EInt tileId) {
	}

	/**
	 * 
	 * @param playerId 
	 * @param edgeId 
	 * @return 
	 */
	public EBoolean canPlaceRoad(EInt playerId, EInt edgeId) {
	}

	/**
	 * 
	 * @param playerId 
	 * @param nodeId 
	 * @param phase 
	 * @return 
	 */
	public EBoolean canPlaceSettlement(EInt playerId, EInt nodeId, Phase phase) {
	}

	/**
	 * 
	 * @param playerId 
	 * @param nodeId 
	 * @return 
	 */
	public EBoolean canUpgradeToCity(EInt playerId, EInt nodeId) {
	}

	/**
	 * 
	 * @param playerId 
	 * @param edgeId 
	 */
	public void placeRoad(EInt playerId, EInt edgeId) {
	}

	/**
	 * 
	 * @param playerId 
	 * @param nodeId 
	 */
	public void placeSettlement(EInt playerId, EInt nodeId) {
	}

	/**
	 * 
	 * @param playerId 
	 * @param nodeId 
	 */
	public void upgradeToCity(EInt playerId, EInt nodeId) {
	}
}
