// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment1PAPYRUS;

/************************************************************/
/**
 * 
 */
public class DicePair implements Dice {
	/**
	 * 
	 */
	public RegularDice die1;
	/**
	 * 
	 */
	public RegularDice die2;

	/**
	 * 
	 * @return 
	 */
	public EInt roll() {
	}
}
