// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment1PAPYRUS;

/************************************************************/
/**
 * 
 */
public interface Dice {
	/**
	 * 
	 * @return 
	 */
	public EInt roll();
}
