// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment1PAPYRUS;

/************************************************************/
/**
 * 
 */
public class Edge {
	/**
	 * 
	 */
	public EInt id;
	/**
	 * 
	 */
	public EInt endpoint1;
	/**
	 * 
	 */
	public EInt endpoint2;
	/**
	 * 
	 */
	public EInt roadOwner;

	/**
	 * 
	 * @param id 
	 * @param endpoint1 
	 * @param endpoint2 
	 */
	public void Edge(EInt id, EInt endpoint1, EInt endpoint2) {
	}

	/**
	 * 
	 * @return 
	 */
	public EBoolean empty() {
	}
}
