// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment1PAPYRUS;

/************************************************************/
/**
 * 
 */
public class Game {
	/**
	 * 
	 * @param maxTurns 
	 */
	public void run(EInt maxTurns) {
	}

	/**
	 * 
	 * @return 
	 */
	public Board board() {
	}

	/**
	 * 
	 * @return 
	 */
	public Phase phase() {
	}

	/**
	 * 
	 * @param p 
	 * @param edgeID 
	 * @param Parameter1 
	 */
	public void buildRoad(Player p, EInt edgeID, EBoolean Parameter1) {
	}

	/**
	 * 
	 * @param p 
	 * @param nodeID 
	 * @return 
	 */
	public EBoolean buildSettlement(Player p, EInt nodeID) {
	}

	/**
	 * 
	 * @param p 
	 * @param nodeID 
	 * @return 
	 */
	public EBoolean upgradeToCity(Player p, EInt nodeID) {
	}
}
