// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment1PAPYRUS;

/************************************************************/
/**
 * 
 */
public class Node {
	/**
	 * 
	 */
	public EInt id;
	/**
	 * 
	 */
	public EInt owner;
	/**
	 * 
	 */
	public BuildingType building;

	/**
	 * 
	 * @param id 
	 */
	public void Node(EInt id) {
	}

	/**
	 * 
	 * @return 
	 */
	public EBoolean empty() {
	}

	/**
	 * 
	 * @param playerID 
	 * @param building 
	 */
	public void setBuilding(EInt playerID, BuildingType building) {
	}
}
