// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment1PAPYRUS;

/************************************************************/
/**
 * 
 */
public class Player {
	/**
	 * 
	 */
	private int id;
	/**
	 * 
	 */
	private EMap hand;
	/**
	 * 
	 */
	public EInt roadsLeft = 15;
	/**
	 * 
	 */
	public EInt settlementsLeft = 5;
	/**
	 * 
	 */
	public EInt citiesLeft = 4;
	/**
	 * 
	 */
	public EInt victoryPoints;

	/**
	 * 
	 * @return 
	 */
	public EInt id() {
	}

	/**
	 * 
	 * @return 
	 */
	public EInt vp() {
	}

	/**
	 * 
	 * @param r 
	 * @param num 
	 */
	public void addResource(Resource r, EInt num) {
	}

	/**
	 * 
	 * @param cost 
	 * @return 
	 */
	public EBoolean hasResources(EMap cost) {
	}

	/**
	 * 
	 * @param cost 
	 */
	public void pay(EMap cost) {
	}

	/**
	 * 
	 * @param game 
	 */
	public void takeTurn(Game game) {
	}

	/**
	 * 
	 * @param n 
	 */
	public void addVictoryPoints(EInt n) {
	}

	/**
	 * 
	 * @return 
	 */
	public EBoolean hasSettlementPiece() {
	}

	/**
	 * 
	 * @return 
	 */
	public EBoolean hasCityPiece() {
	}

	/**
	 * 
	 * @return 
	 */
	public EBoolean hasRoadPiece() {
	}
}
