// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment1PAPYRUS;

/************************************************************/
/**
 * 
 */
public class RegularDice implements Dice {
	/**
	 * 
	 * @return 
	 */
	public EInt roll() {
	}
}
