// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment1PAPYRUS;

/************************************************************/
/**
 * 
 */
public enum Terrain {
	/**
	 * 
	 */
	PASTURE,
	/**
	 * 
	 */
	FOREST,
	/**
	 * 
	 */
	HILLS,
	/**
	 * 
	 */
	FIELD,
	/**
	 * 
	 */
	MOUNTAIN,
	/**
	 * 
	 */
	DESERT;
}
