// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment1PAPYRUS;

/************************************************************/
/**
 * 
 */
public class Tile {
	/**
	 * 
	 */
	public EInt id;
	/**
	 * 
	 */
	public Terrain terrain;
	/**
	 * 
	 */
	public int number;

	/**
	 * 
	 * @param id 
	 * @param terrain 
	 * @param number 
	 */
	public void Tile(EInt id, Terrain terrain, int number) {
	}
}
