// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment1PAPYRUS;

/************************************************************/
/**
 * 
 */
public class TurnManager {
	/**
	 * 
	 */
	public EInt current;
	/**
	 * 
	 */
	public Phase phase;

	/**
	 * 
	 * @return 
	 */
	public EInt currentPlayerIndex() {
	}

	/**
	 * 
	 * @return 
	 */
	public Phase phase() {
	}

	/**
	 * 
	 * @param nPlayers 
	 */
	public void nextTurn(EInt nPlayers) {
	}

	/**
	 * 
	 * @param p 
	 */
	public void setPhase(Phase p) {
	}
}
