// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment1PAPYRUS;

/************************************************************/
/**
 * 
 */
import java.util.Random;

public class RegularDice implements Dice {
	private Random rand = new Random();

	@Override
	public int roll() {
		return rand.nextInt(6) + 1; // 1-6
	}
}