// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment1PAPYRUS;

/************************************************************/
/**
 * 
 */
public class TurnManager {
	private int current = 0;
	private Phase phase = Phase.SETUP;

	public int currentPlayerIndex() {
		return current;
	}

	public Phase phase() {
		return phase;
	}

	public void nextTurn(int nPlayers) {
		current = (current + 1) % nPlayers;
	}

	public void setPhase(Phase p) {
		this.phase = p;
	}
}
